# Changes here will be overwritten by Copier
_commit: f2e3990
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: timkpaine
project_description: Alias for csp-bot
project_name: csp-chatbot
python_version_primary: '3.11'
team: the csp-chatbot authors
